name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0

  firebase_core: ^0.4.0
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^4.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.11.1+3
  cloud_firestore: ^0.12.9



#  firebase_auth: ^0.14.0

#  cloud_firestore: ^0.9.13+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
